### ISSUE TITLE
musicvolume does not actually set music volume

### ISSUE THREAD

**Issue by KeterSCP** [ForNeVeR/bloodmasters#108]
As title says, when specifying `musicvolume = 1;` in the config file, music is still being played with volume taken from `soundsvolume` setting

**Comment by KeterSCP** [comment]
After digging a bit here are my findings:

1. Track is created and played inside `Jukebox`

https://github.com/ForNeVeR/bloodmasters/blob/498800150b1a4ab5f96b08691693bed75568c650/Source/Client/Sound/Jukebox.cs#L77

2. `Track.Play` calls `ApplySettings`, which in turn sets owned `snd.Volume`

https://github.com/ForNeVeR/bloodmasters/blob/498800150b1a4ab5f96b08691693bed75568c650/Source/Client/Sound/Track.cs#L91

https://github.com/ForNeVeR/bloodmasters/blob/498800150b1a4ab5f96b08691693bed75568c650/Source/Client/Sound/Track.cs#L59

3. `Sound.Volume` setter in addition to setting volume itself, also sets `update` flag to `true`

https://github.com/ForNeVeR/bloodmasters/blob/498800150b1a4ab5f96b08691693bed75568c650/Source/Client/Sound/Sound.cs#L39

4. Then, `Track's` `snd.Play` is invoked which calls `Update` on itself and checks if `update` flag is `true`

https://github.com/ForNeVeR/bloodmasters/blob/498800150b1a4ab5f96b08691693bed75568c650/Source/Client/Sound/Track.cs#L92

https://github.com/ForNeVeR/bloodmasters/blob/498800150b1a4ab5f96b08691693bed75568c650/Source/Client/Sound/Sound.cs#L125

5. Due to the fact that `update` was set to true (see `3.`), `_soundSample` sets it's volume to `effectsvolume`

https://github.com/ForNeVeR/bloodmasters/blob/498800150b1a4ab5f96b08691693bed75568c650/Source/Client/Sound/Sound.cs#L158

<br>

So why does this work correctly in the original game? Because `Track's` `snd` field is not actually a custom `Sound` class, but native DirectX `Audio` class, and setting `Volume` property on it is completely different from setting it on custom `Sound` class:

https://sourceforge.net/p/bloodmasters/code/HEAD/tree/trunk/Source/Client/Sound/Track.cs#l32

**Comment by ForNeVeR** [comment]
🤯

**Comment by KeterSCP** [comment]
And again, this was not closed on merge ¯\_(ツ)_/¯

**Comment by ForNeVeR** [comment]
<img width="643" alt="image" src="https://github.com/ForNeVeR/bloodmasters/assets/92793/189323da-6910-47d3-a3c9-1aa77176521c">
Ha-ha.
