### ISSUE TITLE
Restoring minimized window sets ambient sound to full volume for a short time

### ISSUE THREAD

**Issue by KeterSCP** [ForNeVeR/bloodmasters#122]
Steps to reproduce:

1. Enable sounds
2. Run cemetery map
3. Alt-tab or minimize game window
4. Restore it back and notice how background ambient sound is set to full volume for like 100ms

After some bisecting I found that this started happening after https://github.com/ForNeVeR/bloodmasters/pull/94/commits/300e477eddedf0ae58b81b4de69c2af46dfd4796

@ForNeVeR

**Comment by ForNeVeR** [comment]
I see what was happening: before this, the sound was explicitly disabled by that code. Now, it is enabled in 100% volume.

But then, I've decided to remove the setting of it to -10000 because of the previous issue with #103.

Something's wrong there.

**Comment by KeterSCP** [comment]
Yep, in #103, as a temporary workaround, I set initial volume sound to max. But after #107 we can revert that
