### ISSUE TITLE
Return custom and fullscreen mode

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/bloodmasters#14]
Currently, the game client crashes if it's started in fullscreen. We should investigate that.

Also, I've temporarily locked the resolution; we should unlock it back.

See `// TODO[#14]` in the code.

**Comment by KeterSCP** [comment]
So it fails on https://github.com/ForNeVeR/bloodmasters/blob/9a61037bc864bf4edd8fd1b5f23c3619c730ee0e/Source/Client/Graphics/Direct3D.cs#L1156 with with 0x8876086C (D3DERR_INVALIDCALL)

Still have no idea why
