### ISSUE TITLE
Movement controls are defaulted to ESDF instead of WASD

### ISSUE THREAD

**Issue by bookuha** [ForNeVeR/bloodmasters#33]
At this moment. you have to use ESDF keys to move, which I find confusing. I believe that movement should be defaulted to well-known "WASD".

**Comment by ForNeVeR** [comment]
Yep, I agree, let's of course make WASD the default.

**Comment by moldyharriet** [comment]
Mind if I work on this?

**Comment by sotiredofyours** [comment]
@moldyharriet Oops, I think I've already fixed this issue. I didn't see your message :(
But I think @ForNeVeR  won't mind if you take another one. At first glance, #37 looks easy for the first issue.

Answering your question about finding the right files, look at stack trace. Usually all the answers are already there.

**Comment by moldyharriet** [comment]
Awesome, thanks so much!
