### ISSUE TITLE
Support unrar across all the platforms

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/bloodmasters#42]
Bloodmasters seems to use RAR for… some purposes.

Before merge of #27, there was separate support for RAR on Windows and Linux, but I've removed a corresponding conditional compilation block and made Linux implementation to try loading a Windows library (which will obviously fail).

Notably, it would also fail earlier, because the Linux implementation was defunct (wasn't loading any libraries).

We should bring some kind of cross-platform library for RAR and get rid of native libraries (and, while we are at it, also remove the corresponding binaries from the `Build` directory).

See `#42` in the code when performing this operation, I've left a comment where to start.

**Comment by KeterSCP** [comment]
Maybe we can recompress them to ZIP archives, and use existing crossplat zip API from BCL?

**Comment by ForNeVeR** [comment]
I would like to keep compatibility with the old ways and content, if possible. If there is a cross-platform RAR decompressor for .NET, then why not just take and use it?

And if there is no such compressor, then I think I'm ready to consider alternative formats.
