### ISSUE TITLE
Odd laser sight source position

### ISSUE THREAD

**Issue by KeterSCP** [ForNeVeR/bloodmasters#47]
The laser sight's source seems rendered way below the user's position.

[lasersight_bug.webm](https://github.com/ForNeVeR/bloodmasters/assets/38229504/634db04e-e5e9-4a28-9f2f-6f96f1a9261b)

**Comment by KeterSCP** [comment]
After some bisection:

last working commit - https://github.com/ForNeVeR/bloodmasters/commit/ae3703618039c414b457ad119e0598b964cbcd9f
broken since https://github.com/ForNeVeR/bloodmasters/commit/f1de82a193fed0b8ba2d419eda6eb19112a4ead0

But I don't see any change in the commit that could break it

**Comment by ForNeVeR** [comment]
I've seen that issue before ae3703618039c414b457ad119e0598b964cbcd9f, perhaps it's intermittent. We'll need to investigate.
