### ISSUE TITLE
Launcher window gets bigger on every restart

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/bloodmasters#54]
Start **Launcher** app, make it of the smallest size possible:
![image](https://github.com/ForNeVeR/bloodmasters/assets/92793/97648d8d-c95f-4f44-a2e2-32e24e317e4b)

Close and start again.
![image](https://github.com/ForNeVeR/bloodmasters/assets/92793/faa14591-3126-4d1e-9962-4f5ac6ed8623)

And then again.
![image](https://github.com/ForNeVeR/bloodmasters/assets/92793/2bfc4e19-6a2c-48d2-a1fe-249648c9c0b5)

It is about 22% bigger every time.

**Comment by ForNeVeR** [comment]
I suspect it only reproduces on HiDPI, and perhaps it's trying to restore data from `Build/Bloodmasters.cfg` and does something wrong at that.

**Comment by KeterSCP** [comment]
On your screenshots, I see that `Options` and `Exit` buttons are shifted down. This should have been fixed in https://github.com/ForNeVeR/bloodmasters/pull/53

Maybe it is another case of https://github.com/ForNeVeR/bloodmasters/pull/53#issuecomment-1646661465?

**Comment by ForNeVeR** [comment]
For me, they are shifted consistently.

**Comment by KeterSCP** [comment]
> For me, they are shifted consistently.

Yeah, I'm thinking on instead of sharing these two buttons (options and exit) between 2 different panels, make a copy of them for each panel with shared handlers. I've checked it locally, and it seems to work

**Comment by ForNeVeR** [comment]
I've opened #57 about this issue :)
