### ISSUE TITLE
Launcher layout: Options and Exit buttons are a couple of pixels off

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/bloodmasters#57]
<img width="601" alt="image" src="https://github.com/ForNeVeR/bloodmasters/assets/92793/b889d252-a773-494e-980c-e4391a0b2190">

**Options…** and **Exit** are a couple of pixels higher than all the other buttons — in HiDPI, at least.

**Comment by KeterSCP** [comment]
So it is definitely related to scaling:

<details>
<summary>Different scaling percentages</summary>

100%
![image](https://github.com/ForNeVeR/bloodmasters/assets/38229504/674d4745-4fd6-49bf-a934-64c6e983f103)

125%
![image](https://github.com/ForNeVeR/bloodmasters/assets/38229504/eaae0b66-4c82-42fc-8fb1-57bc56497c28)
 
 150%
![image](https://github.com/ForNeVeR/bloodmasters/assets/38229504/c041e1a3-2c5d-4914-9b6b-d5e5ca4d80ce)

200%
![image](https://github.com/ForNeVeR/bloodmasters/assets/38229504/ec816270-f090-47d0-a32a-f4676340496e)
</details>
