### ISSUE TITLE
Black square stays after exiting the game

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/bloodmasters#74]
1. Start the game using `Bloodmasters.Client` default configuration
2. It will start launcher
3. Use launcher to start the game
4. Play the game
5. Exit the game
6. You'll see a black square. Here, it is visible on top of the launcher window.

<img width="696" alt="image" src="https://github.com/ForNeVeR/bloodmasters/assets/92793/04dff59e-c355-44e6-a3a5-bd71da5b0f87">

The game process is still alive at that moment.

Here's the parallel stacks window in case that helps:
<img width="747" alt="image" src="https://github.com/ForNeVeR/bloodmasters/assets/92793/a2276cfa-ea5e-48e3-8b9b-6b8e976dbe3b">

It looks like there's an outstanding call to `SynchronizationContext.Send` somewhere that gets stuck and blocks the runtime from terminating.

**Comment by KeterSCP** [comment]
Is this 100% reproducible on your machine? Because I cannot reproduce it. Do you use fullscreen or windowed mode?

**Comment by ForNeVeR** [comment]
Yes, for me it is stable. I use default settings (i.e. fullscreen).

And if that's important, I exit via `Esc` → **Quit** button.

**Comment by KeterSCP** [comment]
So i can reproduce it on 150% scaling, and not on 125%

**Comment by KeterSCP** [comment]
This should be closed then

**Comment by ForNeVeR** [comment]
Ah, yep.
