### ISSUE TITLE
Starting map from launcher throws exception

### ISSUE THREAD

**Issue by KeterSCP** [ForNeVeR/bloodmasters#86]
Steps to reproduce:

- Run Bloodmasters.Launcher project
- Select any map (in `Host Game` tab)
- Click `Launch` button

Expected result:
- Map is started

Actual result:
![image](https://github.com/ForNeVeR/bloodmasters/assets/38229504/c1a95b7e-d32a-446c-b846-94c36c38fbac)

It seems like regression was caused by https://github.com/ForNeVeR/bloodmasters/pull/81
/cc @ForNeVeR

**Comment by ForNeVeR** [comment]
Could you please clarify what are the contents of said directory?

**Comment by KeterSCP** [comment]
It doesn't even exist, here is a screenshot of the `Source` folder:
![image](https://github.com/ForNeVeR/bloodmasters/assets/38229504/afb4ca5c-f822-45a6-a566-94838452fd3a)
